version: "3.9"

services:
  migrator:
    build:
      context: ../
      dockerfile: ./deployments/images/migrator/Dockerfile    
    links: 
      - db    

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      timeout: 5s
      retries: 30
      start_period: 80s
    ports:
      - 5432:5432    
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: migrator_test
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data:delegated