name: Gomigrator integration test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
        postgres: 
          image: postgres
          env:
            POSTGRES_DB: postgres
            POSTGRES_USER: test
            POSTGRES_PASSWORD: test            
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5        
          ports:          
            - 5432:5432

    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Integration test
        run: make build-and-run-integration-test

